name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        バグの報告ありがとうございます。
  - type: textarea
    id: what-happened
    attributes:
      label: 何が起きましたか？
      description: バグの内容を記述してください。
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現手順
      description: 問題が再現するための手順を記述してください。
      placeholder: 1. Go to '...'
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 環境情報
      description: OS, Antigravity IDE のバージョン, 拡張機能のバージョンなどを記述してください。
    validations:
      required: true
